name: Publish Docker Image
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: docker/metadata-action@v3.6.2
        id: metadata
        with:
          images: ghcr.io/whallin/nextcloud-rc-docker
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}